from pathlib import Path
from itertools import chain, repeat
import inspect
import ast
import re
from textwrap import dedent
from dataclasses import dataclass, field

from fun_django_web.src.page.page import Page
from fun_django_web.src.state_machine.state_machine import StateMachine


_page_re = re.compile(r"(\W|^)(_page.\w+(\.\w+)*)")


@dataclass
class built_resources:
	page_script: Path | None = None
	stylesheets: list[Path] = field(default_factory=list)
	back_methods: Path | None = None
	front_view_class: Path | None = None


def gen_build_resources(
	cls: type,
	view_static_path: Path,
	back_endpoints: list[str],
	back_attr_endpoints: list[str],
	front_functions: list[str],
) -> built_resources:
	reference = built_resources()

	if hasattr(cls, "_page"):
		result = Page._builder_start.copy()
		for child in cls._page.body.children:
			child.builder(output=result)

		script_path = view_static_path / "__script.py"
		script_path.write_text(
			'# Code autogenerated from a Python Page object\n\n' +
			'\n'.join(result)
		)
		reference.page_script = script_path

	static_folder = view_static_path.parent
	if hasattr(cls, '_stylesheets'):
		stylesheets = cls._stylesheets

		if not isinstance(stylesheets, (list, tuple, set)):
			stylesheets = [stylesheets]

		for stylesheet in stylesheets:
			if hasattr(stylesheet, '_output_paths'):
				output_paths = stylesheet._output_paths

				if not isinstance(output_paths, (list, tuple)):
					output_paths = [output_paths]

				output_paths = [
					static_folder / p
					for p in output_paths
				]
			else:
				output_paths = [
					view_static_path / f"{stylesheet.__name__}.css"
				]

			stylesheet_src = (
				'/* CSS autogenrated from a Python CSS object */\n' +
				stylesheet.generate()
			)
			for output_path in output_paths:
				output_path.write_text(
					stylesheet_src
				)

			reference.stylesheets.extend(output_paths)

	if back_endpoints or back_attr_endpoints:
		back_endpoints_src: str = '\n'.join((
			f'def {endpoint_name}(*args, **kwargs): '
			'return asyncio.create_task('
			'make_request('
			f'"{cls._endpoint}/{endpoint_name}",'
			f'method={method!r},'
			'**kwargs'
			'))'
			for endpoint_name, method in chain(
				zip(back_endpoints, repeat('POST')),
				zip(back_attr_endpoints, repeat('GET'))
			)
		))

		back_methods_path = view_static_path / "back_access_endpoint_methods.py"
		back_methods_path.write_text(
			back_endpoints_src
		)
		reference.back_methods = back_methods_path

	front_class_name = "PageView"
	front_class_def = '\n\t'.join([
		f'class {front_class_name}(StateMachine, Reactive):',
		'def __init__(self, *args, **kwargs):',
		'\tfor base in type(self).__bases__:',
		'\t\tbase.__init__(self, *args, **kwargs)'
	])

	glob = globals()
	loc = locals()

	front_var_definitions: list[str] = list()
	source = inspect.getsource(cls.__base__)
	tree = ast.parse(source)
	for node in tree.body[0].body:
		attr_name = None
		segment = None

		if isinstance(node, ast.ClassDef):
			attr_name = node.name

		elif isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name):
				attr_name = node.target.id

		elif isinstance(node, ast.Assign):
			for target in node.targets:
				if isinstance(target, ast.Name):
					attr_name = target.id
					break

		elif (
			isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and 
			not inspect.isfunction(getattr(cls, node.name))
		):
			front_functions.append(ast.unparse(node))
			continue

		elif isinstance(node, ast.Expr) and hasattr(node, "value"):
			segment = ast.get_source_segment(source, node.value)

		else:
			continue

		if attr_name and not attr_name.startswith("_"):
			segment = ast.get_source_segment(source, node)

		if segment:
			try:
				segment = _page_re.sub(
					lambda m: m.group(1) + eval(f"cls.{m.group(2)}", glob, loc),
					segment
				)
			except TypeError:
				raise NameError("Wrong usage of _page")

			front_var_definitions.append(segment)

	# for attr in StateMachine.__annotations__.keys():
	# 	pass

	if front_var_definitions:
		front_var_definitions_src = '\n\t' + '\n\t'.join(front_var_definitions)
	else:
		front_var_definitions_src = ''

	if back_endpoints or back_attr_endpoints:
		front_back_functions_src = '\n\t' + '\n\t'.join([
			f'_{endpoint_name} = {endpoint_name}'
			for endpoint_name in chain(
				back_endpoints,
				back_attr_endpoints,
			)
		])
	else:
		front_back_functions_src = ''

	if front_functions:
		front_functions_src: str = '\n\t' + '\n\t'.join([
			*(
				fn_line
				for fn_line in chain(*(
					dedent(
						front_fn
						if isinstance(front_fn, str)
						else
						inspect.getsource(
							front_fn
						).replace(cls.__base__.__name__, front_class_name)
					).split('\n')
					for front_fn in (
						getattr(cls, front_fn_name, front_fn_name)
						for front_fn_name in front_functions
					)
					if (
						front_fn is not None
						and (
							inspect.isfunction(front_fn)
							or inspect.ismethod(front_fn)
							or inspect.isclass(front_fn)
							or inspect.isbuiltin(front_fn)
							or isinstance(front_fn, str)
						)
					)
				))
				if fn_line.strip()
			)
		])
	else:
		front_functions_src = ''

	if (
		front_functions_src or
		front_back_functions_src or
		front_var_definitions_src
	):
		front_startup_code = getattr(cls, '_front_startup', '')
		if front_startup_code:
			front_startup_code = '\n' + front_startup_code

		front_view_path = view_static_path / "front_view_class.py"
		front_view_path.write_text(
			front_class_def +
			front_var_definitions_src +
			front_back_functions_src +
			front_functions_src +
			'\nview = PageView()\nprint("view initialized")' +
			front_startup_code
		)
		reference.front_view_class = front_view_path

	return reference
