from pathlib import Path
from itertools import chain, repeat
import inspect
from textwrap import dedent

from fun_django_web.src.page.page import Page


def gen_build_resources(
    cls: type,
    view_static_path: Path,
    back_endpoints: list[str],
    back_attr_endpoints: list[str],
    front_functions: list[str],
) -> None:
    if hasattr(cls, "_page"):
        result = Page._builder_start.copy()
        for child in cls._page.body.children:
            child.builder(output=result)

        (view_static_path / "__script.py").write_text(
            '# Code autogenerated from a Python Page object\n\n' +
            '\n'.join(result)
        )

    if hasattr(cls, '_stylesheets'):
        stylesheets = cls._stylesheets

        if not isinstance(stylesheets, (list, tuple, set)):
            stylesheets = [stylesheets]

        for stylesheet in stylesheets:
            (view_static_path / f"{stylesheet.__name__}.css")\
                .write_text(
                    '/* CSS autogenrated from a Python CSS object */\n' +
                    stylesheet.generate()
                )  # noqa: E123

    if back_endpoints or back_attr_endpoints:
        back_endpoints_src: str = '\n'.join((
            f'def {endpoint_name}(*args, **kwargs): '
            'return asyncio.ensure_future('
            'make_request('
            f'"{cls._endpoint}/{endpoint_name}",'
            f'method={method!r},'
            '**kwargs'
            '))'
            for endpoint_name, method in chain(
                zip(back_endpoints, repeat('POST')),
                zip(back_attr_endpoints, repeat('GET'))
            )
        ))

        (view_static_path / "back_access_endpoint_methods.py").write_text(
            back_endpoints_src
        )

    front_class_def = 'class PageView:\n\t'

    if back_endpoints or back_attr_endpoints:
        front_back_functions_src = '\n\t'.join([
            f'_{endpoint_name} = {endpoint_name}'
            for endpoint_name in chain(
                back_endpoints,
                back_attr_endpoints,
            )
        ])
    else:
        front_back_functions_src = ''

    if front_functions:
        front_functions_src: str = '\n\t' + '\n\t'.join([
            *(
                fn_line
                for fn_line in chain(*(
                    dedent(
                        inspect.getsource(
                            getattr(cls, front_fn_name)
                        )
                    ).split('\n')
                    for front_fn_name in front_functions
                ))
                if fn_line.strip()
            )
        ])
    else:
        front_functions_src = ''

    if front_functions_src or front_back_functions_src:
        (view_static_path / "front_view_class.py").write_text(
            front_class_def +
            front_back_functions_src +
            front_functions_src +
            '\nview = PageView()'
        )
