from pathlib import Path
from itertools import chain, repeat
import inspect
import ast
from textwrap import dedent
from dataclasses import  dataclass, field

from fun_django_web.src.page.page import Page


@dataclass
class built_resources:
	page_script: Path | None = None
	stylesheets: list[Path] = field(default_factory=list)
	back_methods: Path | None = None
	front_view_class: Path | None = None


def gen_build_resources(
	cls: type,
	view_static_path: Path,
	back_endpoints: list[str],
	back_attr_endpoints: list[str],
	front_functions: list[str],
) -> built_resources:
	reference = built_resources()

	if hasattr(cls, "_page"):
		result = Page._builder_start.copy()
		for child in cls._page.body.children:
			child.builder(output=result)

		script_path = view_static_path / "__script.py"
		script_path.write_text(
			'# Code autogenerated from a Python Page object\n\n' +
			'\n'.join(result)
		)
		reference.page_script = script_path

	static_folder = view_static_path.parent
	if hasattr(cls, '_stylesheets'):
		stylesheets = cls._stylesheets

		if not isinstance(stylesheets, (list, tuple, set)):
			stylesheets = [stylesheets]

		for stylesheet in stylesheets:
			if hasattr(stylesheet, '_output_paths'):
				output_paths = stylesheet._output_paths

				if not isinstance(output_paths, (list, tuple)):
					output_paths = [output_paths]

				output_paths = [
					static_folder / p
					for p in output_paths
				]
			else:
				output_paths = [
					view_static_path / f"{stylesheet.__name__}.css"
				]

			stylesheet_src = (
				'/* CSS autogenrated from a Python CSS object */\n' +
				stylesheet.generate()
			)
			for output_path in output_paths:
				output_path.write_text(
					stylesheet_src
				)

			reference.stylesheets.extend(output_paths)

	if back_endpoints or back_attr_endpoints:
		back_endpoints_src: str = '\n'.join((
			f'def {endpoint_name}(*args, **kwargs): '
			'return asyncio.create_task('
			'make_request('
			f'"{cls._endpoint}/{endpoint_name}",'
			f'method={method!r},'
			'**kwargs'
			'))'
			for endpoint_name, method in chain(
				zip(back_endpoints, repeat('POST')),
				zip(back_attr_endpoints, repeat('GET'))
			)
		))

		back_methods_path = view_static_path / "back_access_endpoint_methods.py"
		back_methods_path.write_text(
			back_endpoints_src
		)
		reference.back_methods = back_methods_path

	front_class_name = "PageView"
	front_class_def = '\n\t'.join([
		f'class {front_class_name}(StateMachine, Reactive):',
		'def __init__(self, *args, **kwargs):',
		'\tfor base in type(self).__bases__:',
		'\t\tbase.__init__(self, *args, **kwargs)'
	])

	front_var_definitions: list[str] = list()
	source = inspect.getsource(cls.__base__)
	tree = ast.parse(source)
	for node in tree.body[0].body:
		attr_name = None

		if isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name):
				attr_name = node.target.id
		elif isinstance(node, ast.Assign):
			for target in node.targets:
				if isinstance(target, ast.Name):
					attr_name = target.id
		else:
			continue

		if attr_name:
			if attr_name.startswith('_'):
				continue

			segment = ast.get_source_segment(source, node)
			if segment:
				front_var_definitions.append(segment)

	if front_var_definitions:
		front_var_definitions_src = '\n\t' + '\n\t'.join(front_var_definitions)
	else:
		front_var_definitions_src = ''

	if back_endpoints or back_attr_endpoints:
		front_back_functions_src = '\n\t' + '\n\t'.join([
			f'_{endpoint_name} = {endpoint_name}'
			for endpoint_name in chain(
				back_endpoints,
				back_attr_endpoints,
			)
		])
	else:
		front_back_functions_src = ''

	if front_functions:
		front_functions_src: str = '\n\t' + '\n\t'.join([
			*(
				fn_line
				for fn_line in chain(*(
					dedent(
						inspect.getsource(
							getattr(cls, front_fn_name)
						).replace(cls.__base__.__name__, front_class_name)
					).split('\n')
					for front_fn_name in front_functions
				))
				if fn_line.strip()
			)
		])
	else:
		front_functions_src = ''

	if (
		front_functions_src or
		front_back_functions_src or
		front_var_definitions_src
	):
		front_view_path = view_static_path / "front_view_class.py"
		front_view_path.write_text(
			front_class_def +
			front_var_definitions_src +
			front_back_functions_src +
			front_functions_src +
			'\nview = PageView()'
		)
		reference.front_view_class = front_view_path

	return reference
